In [17]:
import pandas as pd
import numpy as np

In [21]:
# Load cleaned data files into pandas DataFrames
# 'ISO-8859-1' encoding is used for building_descriptions_df to handle special characters
# that would cause issues with the default 'utf-8' encoding

yearly_values_df = pd.read_csv("Cleaned Data\cleaned_yearly_values.csv")
sales_data_df = pd.read_csv("Cleaned Data\cleaned_sales_date.csv")
building_descriptions_df = pd.read_csv("Cleaned Data\cleaned_building_descriptions.csv", encoding='ISO-8859-1')

In [5]:
yearly_values_df.head()

,account_num,land_value,building_value,total_value,zip_code,levy_month,levy_year
0,50686170,1417500,1417500,1417500,22039,1,2010
1,50686170,1575000,1575000,1575000,22039,1,2009
2,50686170,1575000,1575000,1575000,22039,1,2008
3,50686170,1575000,1575000,1575000,22039,1,2007
4,50686170,1500000,1500000,1500000,22039,1,2006

In [23]:
sales_data_df.head()

        num  sale_price  sale_month  sale_day  sale_years
0  15890000     1200000           7        23        2009
1  15890000           0           8        20        2004
2  15890000      289000           7        30        1999
3  15890000      259000          10        25        1994
4  15890000      114900           3        22        1985

In [25]:
building_descriptions_df.head()

,account_num,year_built,construction_quality,building_condition,hvac,building_type,gross_building_area,net_leasable_area
0,50466800,1961,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,NaN,NaN
1,50466810,1961,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,NaN,NaN
2,50466820,1961,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,NaN,NaN
3,50466830,1961,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,NaN,NaN
4,50466840,1961,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,NaN,NaN